[package]
name = "mizan-dz"
version = "1.0.0"
description = "Mizan DZ — نظام إدارة المحلات والمبيعات التجاري (Offline First)"
authors = ["Mizan DZ Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "path-all", "process-relaunch", "process-exit", "dialog-all", "fs-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
